// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmdaaykrbqdhhsqvvsrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtZGFheWtyYnFkaGhzcXZ2c3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjE1NDUsImV4cCI6MjA2ODgzNzU0NX0.7x4NcfuRu-uNDTeVU9q79wraiTo6LNNbV52atDCStmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});